//CURRENCY

export const SUBMIT_CURRENCY_CONVERTER = "SUBMIT_CURRENCY_CONVERTER";
export const START_CURRENCY_CONVERTER = "START_CURRENCY_CONVERTER";
export const COMPLETE_CURRENCY_CONVERTER = "COMPLETE_CURRENCY_CONVERTER";
export const FAIL_CURRENCY_CONVERTER = "FAIL_CURRENCY_CONVERTER";